import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css' 
import 'bootstrap/dist/css/bootstrap.min.css';
import Carousel from 'react-bootstrap/Carousel';

import {Button,CardGroup, Card} from 'react-bootstrap';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="/tc.jpg" width="100" height="700"
          alt="First slide"
        />
        <Carousel.Caption>
          <h3>First slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="/b1.jpg" width="100" height="700"
          alt="Second slide"
        />

        <Carousel.Caption>
          <h3>Second slide label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="/c3.jpg" width="100" height="700"
          alt="Third slide"
        />

        <Carousel.Caption>
          <h3>Third slide label</h3>
          <p>
            Praesent commodo cursus magna, vel scelerisque nisl consectetur.
          </p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="/r1.jpg" width="50px" height="700px"
          alt="First slide"
        />
        <Carousel.Caption>
          <h3>First slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </Carousel.Caption>
      </Carousel.Item>
    </Carousel>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.carbike360.com/">CARSBIKE360</a>
        </h1>

        <p className={styles.description}>
         <b> Details about the Cars and Bike</b>
          <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          <a href='' className='styles.card'>
        <h2>Available cars</h2>
          <div className={styles.card}>
            <div>
            <Image className={styles.image} src="/cars.jpg" alt="pic1" width="300px" height="200px" />
            <h3>Terra</h3>
            <h6>Automatic</h6>
            <h3>₹7.97 lakh Onward</h3>
            <h4>
            <div className={styles.links}>
              <a href="/cars/terra"> View Details</a>
              </div>
            </h4>
            </div>
            <div>
            <Image className='styles.card' src="/tc.jpg" alt='pic2' width="300px" height="200px" />
            <h3>Tata Curvv </h3>
            <h6>Manual</h6>
            <h3>₹ 20.00 lakh Onward</h3>
            <h4>
            <div className={styles.links}>
              <a href="/cars/tata"> View Details</a>
              </div>
            </h4>
            </div>
            <div>
            <Image className='styles.image' src="/c3.jpg" alt='pic3' width="300px" height="200px" />
            <h3>Audii</h3>
            <h6>Automatic</h6>
            <h3>₹1.97 Cr Onward</h3>
            
            <h4>
            <div className={styles.links}>
              <a href="/cars/about"> View Details</a>
              </div>
            </h4>
            </div>
            <div>
            <Image className='styles.image' src="/fr.jpg" alt='pic4' width="300px" height="200px" />
            <h3> Fortuner </h3>
            <h6>Manual</h6>
            <h3>₹32-49 lakh Onward</h3>
            <h4>
            <div className={styles.links}>
              <a href="/cars/about"> View Details</a>
              </div>
            </h4>
            
            </div>
            
            </div>
            </a>
            
             </div>
          

          <div className={styles.grid}>
          <a href='' className='styles.card'>
            <h2>Available Bike </h2>
            <div className={styles.card}>
            <div className={styles.box}>
            <Image className={styles.image} src="/b1.jpg" alt='pic1' width="300px" height="200px" />
            <h4> HONDA CBR</h4>
            <h6>Manual</h6>
            <h4>₹1.55 lakh Onward</h4>
            <h4>
           
            <div className={styles.links}>
              <a href="/cars/about"> View Details</a>
              </div>
            </h4>
            </div>
            <div>
            <Image className='styles.image' src="/b2.jpg" alt='pic2' width="300px" height="200px" />
            <h4> Yamaha</h4>
            <h6>Manual</h6>
            <h4>₹ 1.88 lakh Onward</h4>
            <h4>
            <div className={styles.links}>
              <a href="/cars/about"> View Details</a>
              </div>
            </h4>
            </div>
            <div>
              <Image className='styles.image' src="/k.jpg" alt='pic3' width="300px" height="200px"/>
              <h4>KTM</h4>
              <h6>Manual</h6>
              <h4>₹ 2.45 lakh Onward</h4>
              <h4>
                <div className={styles.links}>
              <a href="/cars/about"> View Details</a>
              </div>
            </h4>  
            </div>
            <div>
            <Image className='styles.image' src="/ry.jpg" alt='pic4' width="300px" height="200px"/>
              <h4>ROYAL ENFIELD 350 </h4>
              <h6>Manual</h6>
              <h4>₹ 2.60 lakh Onward</h4>
              <h4>
              <div className={styles.links}>
              <a href="/cars/about"> View Details</a>
              </div>
            </h4>
            </div>
             </div>
             </a>

        </div>
      </main>
      <CardGroup>
      <Card>
        <Card.Img variant="top" src="/cars.jpg" />
        <Card.Body>
          <Card.Title>TERRA</Card.Title>
          <Card.Text>
            This is Fablous Car
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
      <Card>
        <Card.Img variant="top" src="/c3.jpg" />
        <Card.Body>
          <Card.Title>Audi</Card.Title>
          <Card.Text>
            Some Dream For It Others Work For It.{' '}
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
      <Card>
        <Card.Img variant="top" src="/ry.jpg" />
        <Card.Body>
          <Card.Title>ROYAL ENFIELD</Card.Title>
          <Card.Text>
            Made Like a Gun,Goes Like a Bullet.
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
    </CardGroup>

      <footer className={styles.footer}>
        <a
          href="https://www.carbike360.com/"
          rel="Poweredby carbike360"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/logo.PNG" alt="Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
