import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css' 

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.carbike360.com/">CARSBIKE360</a>
        </h1>

        <p className={styles.description}>
          Details about the Cars and Bike
          <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          
            <h2>Available cars &rarr;</h2>
            <div className={styles.card}></div>
            <Image src="/cars.jpg" width="200px" height="200" />
            <h2>Terra</h2>
            <Image src="/c2.jpg" width="200px" height="200" />
            <Image src="/c3.jpg" width="200px" height="200" />
            <Image src="/c4.jpg" width="200px" height="200" />
            
          </div>
          

          <div className={styles.grid}>
            <h2>Available Bike &rarr;</h2>
            <div className={styles.card}>
            <div className={styles.box}>
            
            <Image className={style.image} src="/b1.jpg" alt='pic1' width="300px" height="200" />
            <h3> HONDA Xtream</h3>
            </div>

            <Image src="/b2.jpg" width="300px" height="200" />
            
          </div>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
